apiVersion: v1
kind: Secret
metadata:
    name: blog-secrets
    namespace: blog
type: Opaque
stringData:
    NOTION_TOKEN: ENC[AES256_GCM,data:GBvPdvj+tVNLJ8H4xXlSIEnKOzKVV01SwO3gsQa4JNV0RBusjNrSwRhuP9h6NvzEwrA=,iv:b8qO8mfv8eXmDT0AeXnNYfx+hh3r6k/5bVEAvUQPT4U=,tag:WxAN/r1TzFfLmMABcqDxZw==,type:str]
    NOTION_DATABASE_ID: ENC[AES256_GCM,data:ulVSBuxEGT8pIatNp3CCicmixByeiiVTjKS/O+trMLg=,iv:ual9nvRfsiLMccaTmKE/fPhZVX8x+ry5c0Q0DMLZC+w=,tag:CphsLm97gxS0FkhkzqiC0A==,type:str]
    NOTION_WEBHOOK_SECRET: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMFNPZGs1TzBjMmlHMUhP
            dkR5NFpyUTM1SjdLUENyb2VyRExZckdTQ2wwCjh4a0FwMHdlbGU4Y3BrSy9VaWNF
            VUU1YUFadjdZRDdTOHRQeWVGRFVpcVkKLS0tIE41NlBWM09OcGx0bHZpbXpEVWV1
            OFBObGpIUjNSbDhYMTdyZnFDaWp6T0kKds7FQ5z+YlHsu1gByAmrN6F58ZK/wCuM
            3U3jTSc/QXB3ll07cYyXX8Oy7QjAiPs/xpfGgoHjF5/408C5AO/cow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14y3vjfm4dfz6pr9fz7ndclpa24avmk9ewn3eadfh2fylmnenkp8qqygz4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T05:30:17Z"
    mac: ENC[AES256_GCM,data:lEDdLkJSijIzp/gtekMx5Ai6QzbKlP7imcB0clL8WlZT7c9a6CeEuzd61DsJfN9xWEKqLDOXwTmI81fhHutHnQgrkXY5sFnqsmih/FMG3p+sWLw4mmOXSCmEMJRAdedsdOUNUYLbLhTt8Thnch/9M4Uk3Sh3XrmruKMWJ3ojal0=,iv:c/iSaG4Mgjcq7gS0fS/F4rHNu81uUsTOu3HEk6DZ84Q=,tag:mggPnOPcc2t4OE886AhZ5A==,type:str]
    version: 3.13.1
