apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: tailscale
type: Opaque
stringData:
    #ENC[AES256_GCM,data:FLu9r2cC/bj9VQpsYK81ZwDjk+UYzfFjjGCuBZWr30UC/apKPsxEVNpgjuzj5arwV0FsIskZ2Vo3uVWYko1S8HnB/XyQ/ypxYRMQBhs=,iv:eXAlcSPVSjomKwitS+96By5K2eRdQ3sGgtH2lWP8xIw=,tag:HRau2iQdKQbrbktAPOxpug==,type:comment]
    #ENC[AES256_GCM,data:JQFQyprW4lsyAQdp3k+Lo30fvIDeaZ/UuMyPf0QDkAf3bpzlTmLEwVOoNyqjeqtKKiaqcztUBeE=,iv:lstsCYUx+Ys0+LUDXzrd6zjscLd3EkWBcalkSDQkBQ4=,tag:y2ogBJ0vVE5BozI00weGVg==,type:comment]
    #ENC[AES256_GCM,data:2dM6tN7K9G1eMWBbHVlFoh6QVnWClx4nx62TSH9nm882BxomW7c0wglcU6lGNmWQ0GXy5yQIXC4yNucWZfo=,iv:B9ViTQC117UGqdso5xxVaJmeWOraFms6eK4/AW+vIlU=,tag:Q2WDm14c/HIchRH2fPPigg==,type:comment]
    #ENC[AES256_GCM,data:9ynJwxgBeU6nV5a4n/v6VAyHrqD02g6LsdzVODJcUb7Zk6Nl4k/aX0OrW/7CjhrOfuxP/G8NG4IqFHLPgIinA42Hzd82xCOBCg==,iv:LQMqXFHRCokrIpezCZnLDXnxBcvCK0MiA8yWqAiDpmU=,tag:8cI1rWNQPgszLrnTKS0VEQ==,type:comment]
    #ENC[AES256_GCM,data:NDRDkCwnvRmSbyj8TOKudqBMGC3R14eWYWJACaw9YNjWUYnk3PemtLZS,iv:aUkaxM8MiJ+jCQtG8jvxpYC1UyiRKpuz85zcfENIruc=,tag:9YaDQtkhaXRXLCqgrQa/Qg==,type:comment]
    TS_AUTHKEY: ENC[AES256_GCM,data:ZMqZw5D4ehZENPb0p30AanIHEkKuVERL/v/iSOHeJEe++uS79ksd2t57bQXIfs2HQcOAcP0HqdM51Mzb6g==,iv:kerT8aSIqWyhWkfV0EeZzEDYSZPqypozh1iJV0K+894=,tag:zC8Azq54SOyrv/tLNbrlnQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNTg5VWNmUlAvUW5mTE1W
            UjFSWjVzeW16dVVNajI3eEpGUitFdEFKUmdJCjBEVUxoTmxRcndvWGxPMDBQUmti
            RE92SWNRSkF2dWltWE1IbStRSjJUaVEKLS0tIHF5ZmkxYUF0WGFuYTR5dTNyWklV
            N3dZKzNHYzVUZGt5VFhWR0ROZEhkZU0KCJ7fjssPZf4Z4jXszJT86W8lIQNit0bu
            FXv4ecjczwgKhAqCkYCYGwTcSJUoAVsqytS2eg6Pn7i3Kn3Ci/ELwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14y3vjfm4dfz6pr9fz7ndclpa24avmk9ewn3eadfh2fylmnenkp8qqygz4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T15:58:10Z"
    mac: ENC[AES256_GCM,data:LrNOrG/FPLqutEFy6MsJDp43HE9iNCi6f56M15khQaWaQm4NaHcBKFqeoIOp9SxIuYh18ii9Y3eec4qLBNlFmjnWNjroNFWdB/oRRQI8fxjYa8IiMA9QpAaXTNdCpPzk8RAWYIo+lISOh1MzYPjmC6yQ8E6j/o4KxyD4ryOVs50=,iv:WUjflmX3yuRhM/si40SsuGazw/BlHeAuyxa5H7407W8=,tag:3A29B/ZKFhpTqcGbLZgZWA==,type:str]
    version: 3.13.1
