apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:KhPIpH0YsHegb7K9KjwexNogwwXfUPGIyuHU1nyUcXaDNUW8/NzPxWVgYwUE3MABljOQ2HVFqtMohS26zkJ6sUOI0EU5K+0+3H3ELQ==,iv:dx4lhTYb4fukERhSjDPD94CEFOk8N5mW1gE1bVnkrNY=,tag:8vBg09PeBqPn7wYyb4eX6A==,type:comment]
    #ENC[AES256_GCM,data:X08s3TD0VgJA5VGMDMGxngEGcagWRmuOx2GEKbOxS/rP6kVeeR/RdReWZ4abwZ4u2XFvc0uGlIzQw437922y9e3ErpBlz6gf9xbWWehOLj6M9x0=,iv:JUfZANsDGn8oTFRgl78+8/w/7A4YbTyqY9rTY1nvJhU=,tag:1UfAE6NgGOtLlZg7tPqzOQ==,type:comment]
    client_id: ENC[AES256_GCM,data:hgeXoF7ANWluUFGHFmZxKkw=,iv:AnbXZAYw9YioAG97CHVtW1JjEhGXlJkbhxdB1eKwHEU=,tag:XcvJGH0u4V4dkOE4qR5nEw==,type:str]
    client_secret: ENC[AES256_GCM,data:stW1mWCJ9LZsZDTJpfQ7PVEWWvEESV+qrqCTDIjJKdO66JYkdKH6Z6vvl934LFdP95eKOI5nAqx2oQM9KYurVw==,iv:3K20Q1pwTvfj1iLQGn1dRrC5NPgBk4AxkZA8Ag5E2mQ=,tag:q63Wu1hA5Hj8e0N/cpDn6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSi9RUkZBaXNCNW9CRGJV
            aERORW1YZ2dQSkRWWUxEeVA5VkFra2VxMEc4Ci9XdHFPL0EyTGtZZk5vZVlXaS9m
            ZEYvMXFDRTU2ZGY2Zm1xYWlxVllSaHcKLS0tIDdBUUdjZ3FLRjhUc250bkIwNE5V
            Zmx3eDVIQktFTC9ocHNzdkhITUhaWjAKqWIMlCOK0QcR2pCNg1V6I7jtyshG+IVG
            AUTFma4cZT/YSB506XmbYozVDLXAh6UnvKqZ6Z69/wQBrrzFqRXNMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14y3vjfm4dfz6pr9fz7ndclpa24avmk9ewn3eadfh2fylmnenkp8qqygz4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T07:51:55Z"
    mac: ENC[AES256_GCM,data:VRw5kJVnSbUL+dteK6Jfi9ggkmkEAuTCLlDvOCo8PQdgvrH4h+caH0Z3ub1EJxZH+wbR2h2lXgIxNOn/0jeAJbyKyweBRCufMrQvZCNvr6wYcxyWIPipcTAPHfizHZ07EcodPlYVNFJJ70jXLhgCi7pAr4IaynOQzKGa0DS3ZJY=,iv:aHE7unyPaBxKGmkVT5bgUM2bE15KIR/W0gmY90CEIsE=,tag:0VPK3BtsRAlrSCdv/h3j4Q==,type:str]
    version: 3.13.1
