apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:KhPIpH0YsHegb7K9KjwexNogwwXfUPGIyuHU1nyUcXaDNUW8/NzPxWVgYwUE3MABljOQ2HVFqtMohS26zkJ6sUOI0EU5K+0+3H3ELQ==,iv:dx4lhTYb4fukERhSjDPD94CEFOk8N5mW1gE1bVnkrNY=,tag:8vBg09PeBqPn7wYyb4eX6A==,type:comment]
    #ENC[AES256_GCM,data:X08s3TD0VgJA5VGMDMGxngEGcagWRmuOx2GEKbOxS/rP6kVeeR/RdReWZ4abwZ4u2XFvc0uGlIzQw437922y9e3ErpBlz6gf9xbWWehOLj6M9x0=,iv:JUfZANsDGn8oTFRgl78+8/w/7A4YbTyqY9rTY1nvJhU=,tag:1UfAE6NgGOtLlZg7tPqzOQ==,type:comment]
    client_id: ENC[AES256_GCM,data:/LEZ5Kui87W/4A==,iv:e2F5HdRgjBxzU3UDc4YVO/yYuVV2WyqPdWjrfPLmtg0=,tag:RztKowEBIWaG3aSQNiIH5g==,type:str]
    client_secret: ENC[AES256_GCM,data:hpc0/uHOMMC+Lg==,iv:e+JSB3migwgcW3cHH4isdy8RrhqLUizOeAxD67dxlUQ=,tag:5d558XCOv2st0BgmZmyZQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSi9RUkZBaXNCNW9CRGJV
            aERORW1YZ2dQSkRWWUxEeVA5VkFra2VxMEc4Ci9XdHFPL0EyTGtZZk5vZVlXaS9m
            ZEYvMXFDRTU2ZGY2Zm1xYWlxVllSaHcKLS0tIDdBUUdjZ3FLRjhUc250bkIwNE5V
            Zmx3eDVIQktFTC9ocHNzdkhITUhaWjAKqWIMlCOK0QcR2pCNg1V6I7jtyshG+IVG
            AUTFma4cZT/YSB506XmbYozVDLXAh6UnvKqZ6Z69/wQBrrzFqRXNMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14y3vjfm4dfz6pr9fz7ndclpa24avmk9ewn3eadfh2fylmnenkp8qqygz4h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T05:30:17Z"
    mac: ENC[AES256_GCM,data:86VpQC94jAjVcHYZvmnTYTROhwgYZwAnUqBR2laPzdBvcLwNUdX25jxhIkiN7eH47ugXfCPLHng8w3fo2rUu7dBv2RM3+xmRJ9NGIQFmmTHATD7T2L0V9pb3SlKqD8c0FsT1QB7RUtYLVZzinWltryZK3HWCTFDpdj9/cvU2w+E=,iv:kum7KzGF+3ArOw50w0ZvieVXMf2HdugR5X3BFCQcsvM=,tag:yzeOZR+ChHoqr7ipxnE6mA==,type:str]
    version: 3.13.1
